const project_list = [
  {
    id: 1,
    name: 'MusyCharts',
    description:
      'Aplicación web interactiva que transforma tus datos de Spotify en visualizaciones dinámicas y atractivas. Descubre tus patrones de escucha, artistas favoritos y géneros más reproducidos a través de gráficos interactivos.',
    longDescription:
      'MusyCharts es una aplicación de análisis de datos musicales que conecta con la API de Spotify para extraer y visualizar estadísticas personalizadas de escucha. Utiliza amCharts 5 para crear visualizaciones dinámicas e interactivas que revelan insights sobre hábitos musicales, géneros predominantes y evolución temporal del gusto musical.',
    date: '2023',
    client: 'Proyecto Personal',
    category: 'Data Visualization',
    tags: ['Vue.js', 'Vuetify', 'Spotify API', 'amCharts 5', 'OAuth 2.0'],
    online: true,
    repo: true,
    technologies: 'Vue.js, Vuetify, Spotify API, amCharts 5, OAuth 2.0',
    features: [
      'Autenticación OAuth 2.0 con Spotify',
      'Visualización de top tracks y artistas por período',
      'Análisis de géneros musicales con gráficos de distribución',
      'Dashboard interactivo con múltiples vistas',
      'Diseño responsive y moderno',
    ],
    challenges: [
      'Implementación de flujo OAuth seguro',
      'Optimización de consultas a la API de Spotify',
      'Creación de visualizaciones de datos complejas y performantes',
    ],
    impact: 'Más de 500 usuarios activos descubriendo sus estadísticas musicales',
    images: {
      0: '/img/projects/musycharts-pics/0.jpeg',
      1: '/img/projects/musycharts-pics/1.jpeg',
      2: '/img/projects/musycharts-pics/2.jpeg',
      3: '/img/projects/musycharts-pics/3.jpeg',
    },
    link: 'https://musycharts-dcdv.vercel.app/',
    link_repo: 'https://github.com/daiv05/musycharts-dcdv',
  },
  {
    id: 2,
    name: 'Sistema de Gestión Carmencita',
    description:
      'Plataforma integral de gestión empresarial diseñada específicamente para pequeñas y medianas tiendas. Sistema completo de inventario, facturación, gestión de empleados, planillas y control de pedidos a domicilio.',
    longDescription:
      'Sistema ERP desarrollado a medida para optimizar las operaciones comerciales de una tienda local. Incluye módulos interconectados para gestión de inventario en tiempo real, sistema de punto de venta, administración de recursos humanos con cálculo automático de planillas, y plataforma de gestión de pedidos delivery con seguimiento en tiempo real.',
    date: '2023',
    client: 'Tienda y Depósito "Carmencita"',
    category: 'Enterprise Software',
    tags: ['Vue.js', 'Laravel', 'MySQL', 'TailwindCSS', 'REST API', 'JWT'],
    online: false,
    repo: false,
    technologies: 'Vue.js, TailwindCSS, Laravel, MySQL, Redis',
    features: [
      'Sistema de inventario con alertas de stock bajo',
      'Punto de venta con impresión de facturas',
      'Gestión de empleados y cálculo automático de planillas',
      'Sistema de pedidos a domicilio con seguimiento GPS',
      'Panel administrativo con reportes y analytics',
      'Sistema de roles y permisos granulares',
      'Notificaciones en tiempo real',
    ],
    challenges: [
      'Sincronización de inventario en tiempo real entre múltiples puntos de venta',
      'Implementación de sistema de caché para optimizar consultas frecuentes',
      'Desarrollo de módulo de reportes con exportación a Excel/PDF',
    ],
    impact: 'Reducción del 40% en tiempo de facturación y mejora del 60% en control de inventario',
    images: {
      0: '/img/projects/carmencita-pics/0.png',
      1: '/img/projects/carmencita-pics/1.jpeg',
      2: '/img/projects/carmencita-pics/2.png',
      3: '/img/projects/carmencita-pics/3.png',
      4: '/img/projects/carmencita-pics/4.png',
      5: '/img/projects/carmencita-pics/5.jpeg',
    },
    link: '#',
    link_repo: '#',
  },
  {
    id: 3,
    name: 'RatioInsights',
    description:
      'Herramienta de análisis financiero empresarial que calcula automáticamente ratios financieros clave y los compara con benchmarks de la industria. Importación directa desde Excel para agilizar el análisis.',
    longDescription:
      'Plataforma de análisis financiero que permite a empresas y analistas evaluar la salud financiera mediante el cálculo automático de ratios de liquidez, rentabilidad, endeudamiento y eficiencia. Incluye comparación con estándares de la industria y generación de reportes ejecutivos.',
    date: '2023',
    client: 'Proyecto Universitario',
    category: 'FinTech',
    tags: ['Vue.js', 'Laravel', 'MySQL', 'TailwindCSS', 'SheetJS', 'Chart.js'],
    online: false,
    repo: true,
    technologies: 'Vue.js, TailwindCSS, Laravel, MySQL, SheetJS (xlsx), Chart.js',
    features: [
      'Importación de estados financieros desde Excel',
      'Cálculo automático de 20+ ratios financieros',
      'Comparación con promedios de la industria',
      'Visualización de tendencias históricas',
      'Generación de reportes ejecutivos en PDF',
      'Dashboard de indicadores clave de rendimiento',
    ],
    challenges: [
      'Procesamiento y validación de archivos Excel complejos',
      'Implementación de algoritmos de cálculo de ratios financieros',
      'Diseño de visualizaciones claras para datos financieros complejos',
    ],
    impact: 'Reducción de 70% en tiempo de análisis financiero manual',
    images: {
      0: '/img/projects/ratios-pics/1.jpeg',
      1: '/img/projects/ratios-pics/2.jpeg',
      2: '/img/projects/ratios-pics/3.png',
      3: '/img/projects/ratios-pics/4.png',
      4: '/img/projects/ratios-pics/5.png',
      5: '/img/projects/ratios-pics/6.png',
    },
    link: '#',
    link_repo: 'https://github.com/daiv05/ratios-sis',
  },
  {
    id: 4,
    name: 'CheRooms SV',
    description:
      'Plataforma social para conectar personas que buscan roommates en San Salvador. Sistema de perfiles, matching por preferencias y chat en tiempo real para facilitar la búsqueda de compañeros de vivienda.',
    longDescription:
      'Red social especializada que facilita la búsqueda de compañeros de cuarto en San Salvador. Incluye sistema de perfiles verificados, algoritmo de matching basado en preferencias (presupuesto, ubicación, estilo de vida), chat en tiempo real y sistema de reseñas de usuarios.',
    date: '2022',
    client: 'Proyecto Universitario',
    category: 'Social Platform',
    tags: ['Vue.js', 'Django', 'PostgreSQL', 'WebSockets', 'REST Framework'],
    online: false,
    repo: true,
    technologies: 'Vue.js, Django, PostgreSQL, Django Channels, WebSockets',
    features: [
      'Sistema de registro y autenticación con verificación de email',
      'Perfiles de usuario con preferencias y requisitos',
      'Algoritmo de matching por compatibilidad',
      'Chat en tiempo real entre usuarios',
      'Sistema de búsqueda avanzada con filtros',
      'Publicación y gestión de anuncios de habitaciones',
      'Sistema de reseñas y valoraciones',
    ],
    challenges: [
      'Implementación de WebSockets para chat en tiempo real',
      'Desarrollo de algoritmo de matching efectivo',
      'Gestión de privacidad y seguridad de datos personales',
    ],
    impact: 'Conectó a más de 200 estudiantes en búsqueda de vivienda compartida',
    images: {
      0: '/img/projects/roomies-pics/0.png',
      1: '/img/projects/roomies-pics/1.png',
      2: '/img/projects/roomies-pics/2.png',
      3: '/img/projects/roomies-pics/3.jpeg',
    },
    link: '#',
    link_repo: 'https://github.com/daiv05/cherooms-proy',
  },
];

export default project_list;
