const tutos_list = [
  {
    id: 1,
    name: 'VM Linux en Azure',
    description: 'Crea una máquina virtual desde 0 en Azure.',
    date: '2022',
    author: 'David Deras',
    category: 'Cloud',
    tags: ['Azure', 'Cloud', 'Máquina Virtual', 'Linux'],
    online: true,
    technologies: 'Linux, Azure',
    image: '/img/tutos/azure-vm.jpeg',
    link: 'https://musycharts-dcdv.vercel.app/',
    color: 'blue-grey-lighten-5',
  },
  {
    id: 2,
    name: 'Cuenta .edu en Azure',
    description:
      'Crea una cuenta en Azure utilizando un email .edu, recibiendo un credito de $100. Sin tarjeta.',
    date: '2022',
    category: 'Cloud',
    author: 'David Deras',
    tags: ['Azure', 'Cloud'],
    online: true,
    technologies: 'Azure',
    image: '/img/tutos/azure-account.png',
    link: 'https://musycharts-dcdv.vercel.app/',
    color: 'blue-grey-lighten-4',
  },
  {
    id: 3,
    name: 'Guia Herramientas HDP v.5.2',
    description:
      'Guia completa para la configuración e instalación de las herramientas utilizadas en HDP (RHEL 7 version).',
    date: '2022',
    category: 'Cloud',
    author: 'David Deras',
    tags: ['Azure', 'RedHat 7', 'RHEL 7', 'Máquina Virtual', 'Linux'],
    online: true,
    technologies: 'Linux, Azure, RedHat 7',
    image: '/img/tutos/hdp-herramientas.png',
    link: 'https://musycharts-dcdv.vercel.app/',
    color: 'blue-grey-lighten-3',
  },
  {
    id: 4,
    name: 'LAMPP 5 en RHEL 7',
    description:
      'Guia completa para la configuración e instalación de un servidor LAMPP (PHP 5.6) en RedHat 7.',
    date: '2022',
    category: 'Cloud',
    author: 'David Deras',
    tags: ['Azure', 'RedHat 7', 'RHEL 7', 'Máquina Virtual', 'Linux'],
    online: true,
    technologies: 'Linux, Azure, RedHat 7',
    image: '/img/tutos/rhel7-lampp56.png',
    link: 'https://musycharts-dcdv.vercel.app/',
    color: 'blue-grey-lighten-2',
  },
  {
    id: 5,
    name: 'Desplegando una API Laravel',
    description:
      'Descubre como desplegar una API Laravel 10 en Railway, utilizando una base de datos MySQL.',
    date: '2023',
    category: 'Cloud',
    author: 'David Deras',
    tags: ['Railway', 'Laravel', 'API'],
    online: true,
    technologies: 'Railway, Laravel, API',
    image: '/img/tutos/laravel-railway.png',
    link: 'https://musycharts-dcdv.vercel.app/',
    color: 'blue-grey-lighten-3',
  },
  {
    id: 6,
    name: 'Desplegando Vue.js App',
    description: 'Descubre como desplegar una aplicación Vue.js en Vercel.',
    date: '2023',
    category: 'Cloud',
    author: 'David Deras',
    tags: ['Vue.js', 'Vercel'],
    online: true,
    technologies: 'Vue.js, Vercel',
    image: '/img/tutos/vue-vercel.png',
    link: 'https://musycharts-dcdv.vercel.app/',
    color: 'blue-grey-lighten-4',
  },
];

export default tutos_list;
